export { useDesktopStore } from './desktop'
export { useWindowStore } from './window'
export { useDesktopItemsStore } from './desktopItems'
export { useDesktopSelectionStore } from './desktopSelection'
export { useFsDragStore } from './fsDrag'
export { useSettingsStore, patchSettings, type SettingsPatch } from './settings'
export { useNotepadStore } from './notepad'
export { usePaintStore } from './paint'
export { useKlineChartStore } from './klineChart'
export { useSokobanProgressStore } from './sokoban'
export { useSudokuProgressStore } from './sudoku'
export { useSpiderStore } from './spider'
export { useCalendarStore, dateKeyFromDate } from './calendar'
export { useImageViewerStore } from './imageViewer'
export { useDesktopVfsStore } from './desktopVfs'
