export { useDesktopStore } from './desktop'
export { useWindowStore } from './window'
export { useDesktopItemsStore } from './desktopItems'
export { useSettingsStore, patchSettings, type SettingsPatch } from './settings'
export { useNotepadStore } from './notepad'
export { usePaintStore } from './paint'
export { useCalendarStore, dateKeyFromDate } from './calendar'
export { useDemoAppsStore, DEMO_STAKE_APY, DEMO_CLAIM_COOLDOWN_MS } from './demoApps'
