/**
 * 内置应用统一注册表。
 * 新增应用：在 features/<name>/ 实现 UI，再于此追加一条（显示名写 messages.*.apps.<id>）。
 */
import {
  AppWindow,
  Blocks,
  BookOpenText,
  Bomb,
  Bot,
  Box,
  Calculator,
  ChartCandlestick,
  Cherry,
  Club,
  CodeXml,
  FileText,
  Folder,
  Grid3x3,
  HardDrive,
  ImageIcon,
  Notebook,
  Palette,
  Puzzle,
  ScrollText,
  Settings,
  Shapes,
  Table2,
  Terminal,
  Trash2,
} from 'lucide-react'
import { registerBuiltinApps } from './defineApp'
import { spawnExplorerWindow } from './explorerWindows'
import { spawnIdeEditor } from './ideWindows'
import { spawnOfficeWindow } from './officeWindows'
import { BuiltinAppId } from '@/config/desktop'

registerBuiltinApps([
  {
    id: BuiltinAppId.Games,
    icon: Folder,
    defaultCoordinate: [0, 1],
    width: 360,
    height: 320,
    loadApp: () => import('@/features/games').then((m) => m.GamesApp),
  },
  {
    id: BuiltinAppId.Minesweeper,
    icon: Bomb,
    defaultCoordinate: [1, 1],
    width: 420,
    height: 560,
    showOnDesktop: false,
    showInStartMenu: false,
    loadApp: () => import('@/features/games/minesweeper').then((m) => m.Minesweeper),
  },
  {
    id: BuiltinAppId.Tetris,
    icon: Blocks,
    defaultCoordinate: [1, 2],
    width: 560,
    height: 640,
    showOnDesktop: false,
    showInStartMenu: false,
    loadApp: () => import('@/features/games/tetris').then((m) => m.Tetris),
  },
  {
    id: BuiltinAppId.Suika,
    icon: Cherry,
    defaultCoordinate: [0, 1],
    width: 520,
    height: 760,
    showOnDesktop: false,
    showInStartMenu: false,
    chrome: { resizable: false },
    loadApp: () => import('@/features/games/suika').then((m) => m.Suika),
  },
  {
    id: BuiltinAppId.ImagePuzzle,
    icon: Puzzle,
    defaultCoordinate: [0, 3],
    width: 440,
    height: 620,
    showOnDesktop: false,
    showInStartMenu: false,
    loadApp: () => import('@/features/games/image-puzzle').then((m) => m.ImagePuzzle),
  },
  {
    id: BuiltinAppId.CanvasJigsaw,
    icon: Shapes,
    defaultCoordinate: [0, 4],
    width: 520,
    height: 680,
    showOnDesktop: false,
    showInStartMenu: false,
    loadApp: () => import('@/features/games/canvas-jigsaw').then((m) => m.CanvasJigsaw),
  },
  {
    id: BuiltinAppId.Sokoban,
    icon: Box,
    defaultCoordinate: [0, 5],
    width: 440,
    height: 640,
    showOnDesktop: false,
    showInStartMenu: false,
    loadApp: () => import('@/features/games/sokoban').then((m) => m.Sokoban),
  },
  {
    id: BuiltinAppId.Sudoku,
    icon: Grid3x3,
    defaultCoordinate: [1, 4],
    width: 400,
    height: 620,
    showOnDesktop: false,
    showInStartMenu: false,
    loadApp: () => import('@/features/games/sudoku').then((m) => m.Sudoku),
  },
  {
    id: BuiltinAppId.Spider,
    icon: Club,
    defaultCoordinate: [1, 5],
    width: 1040,
    height: 720,
    showOnDesktop: false,
    showInStartMenu: false,
    chrome: { resizable: true },
    loadApp: () => import('@/features/games/spider').then((m) => m.Spider),
  },
  {
    id: BuiltinAppId.Document,
    icon: BookOpenText,
    defaultCoordinate: [1, 3],
    width: 520,
    height: 420,
    loadApp: () => import('@/features/document').then((m) => m.DocumentApp),
  },
  {
    id: BuiltinAppId.Log,
    icon: Notebook,
    defaultCoordinate: [1, 4],
    width: 520,
    height: 420,
    loadApp: () => import('@/features/log').then((m) => m.LogApp),
  },
  {
    id: BuiltinAppId.Notepad,
    icon: FileText,
    defaultCoordinate: [2, 1],
    width: 560,
    height: 460,
    loadApp: () => import('@/features/notepad').then((m) => m.NotepadApp),
  },
  {
    id: BuiltinAppId.Ide,
    icon: CodeXml,
    defaultCoordinate: [4, 1],
    width: 720,
    height: 520,
    loadApp: () => import('@/features/ide').then((m) => m.IdeApp),
    beforeOpen: () => {
      spawnIdeEditor()?.open()
      return false
    },
  },
  {
    id: BuiltinAppId.Paint,
    icon: Palette,
    defaultCoordinate: [2, 2],
    width: 720,
    height: 560,
    loadApp: () => import('@/features/paint').then((m) => m.PaintApp),
  },
  {
    id: BuiltinAppId.Settings,
    icon: Settings,
    defaultCoordinate: [2, 3],
    width: 560,
    height: 520,
    loadApp: () => import('@/features/settings').then((m) => m.SettingsApp),
  },
  {
    id: BuiltinAppId.Calculator,
    icon: Calculator,
    defaultCoordinate: [2, 4],
    width: 320,
    height: 480,
    chrome: { resizable: false, maximizable: false },
    loadApp: () => import('@/features/calculator').then((m) => m.CalculatorApp),
  },
  {
    id: BuiltinAppId.RecycleBin,
    icon: Trash2,
    defaultCoordinate: [1, 5],
    width: 640,
    height: 440,
    showInStartMenu: false,
    loadApp: () => import('@/features/recycle-bin').then((m) => m.RecycleBinApp),
  },
  {
    id: BuiltinAppId.Cmd,
    icon: Terminal,
    defaultCoordinate: [3, 1],
    width: 640,
    height: 400,
    loadApp: () => import('@/features/cmd').then((m) => m.CmdApp),
  },
  {
    id: BuiltinAppId.KlineChartViewer,
    icon: ChartCandlestick,
    defaultCoordinate: [3, 2],
    width: 1024,
    height: 768,
    loadApp: () => import('@/features/kline-chart').then((m) => m.KlineChartViewer),
  },
  {
    id: BuiltinAppId.AiChat,
    icon: Bot,
    defaultCoordinate: [3, 3],
    width: 560,
    height: 520,
    loadApp: () => import('@/features/ai-chat').then((m) => m.AiChatApp),
  },
  {
    id: BuiltinAppId.TaskManager,
    icon: AppWindow,
    defaultCoordinate: [3, 4],
    width: 420,
    height: 480,
    loadApp: () => import('@/features/task-manager').then((m) => m.TaskManagerApp),
  },
  {
    id: BuiltinAppId.ImageViewer,
    icon: ImageIcon,
    defaultCoordinate: [3, 5],
    width: 760,
    height: 560,
    loadApp: () => import('@/features/image-viewer').then((m) => m.ImageViewerApp),
  },
  {
    id: BuiltinAppId.FileExplorer,
    icon: HardDrive,
    defaultCoordinate: [2, 5],
    width: 720,
    height: 480,
    loadApp: () => import('@/features/file-explorer').then((m) => m.FileExplorerApp),
    beforeOpen: () => {
      spawnExplorerWindow({ path: '/' })?.open()
      return false
    },
  },
  {
    id: BuiltinAppId.Writer,
    icon: ScrollText,
    defaultCoordinate: [5, 1],
    width: 720,
    height: 520,
    loadApp: () => import('@/features/office').then((m) => m.WriterApp),
    beforeOpen: () => {
      spawnOfficeWindow({ kind: 'writer' })?.open()
      return false
    },
  },
  {
    id: BuiltinAppId.Sheet,
    icon: Table2,
    defaultCoordinate: [5, 2],
    width: 780,
    height: 520,
    loadApp: () => import('@/features/office').then((m) => m.SheetApp),
    beforeOpen: () => {
      spawnOfficeWindow({ kind: 'sheet' })?.open()
      return false
    },
  },
])
